# Generated by Django 5.2.11 on 2026-02-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Nomi')),
                ('short_description', models.TextField(verbose_name='Qisqa tavsif')),
                ('how_it_works', models.TextField(help_text='Har bir bosqichni yangi qatordan yozing.', verbose_name='Qanday ishlaydi')),
                ('technologies', models.CharField(help_text='Masalan: Django, DRF, PostgreSQL', max_length=255, verbose_name='Texnologiyalar')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub havolasi')),
                ('live_url', models.URLField(blank=True, verbose_name='Demo havolasi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Rasm')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy loyihami?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateField(verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
