# Generated by Django 5.2.11 on 2026-02-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_bookingrequest_funnelevent_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='metric_after',
            field=models.CharField(blank=True, default='', help_text='Masalan: API response 320ms', max_length=180, verbose_name='After metrika'),
        ),
        migrations.AddField(
            model_name='project',
            name='metric_before',
            field=models.CharField(blank=True, default='', help_text='Masalan: API response 1.8s', max_length=180, verbose_name='Before metrika'),
        ),
    ]
